# appspec.yml

version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/idea_backend/backend
    overwrite: yes
files_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: backend/scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: backend/scripts/start.sh
      timeout: 60
      runas: ubuntu