spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:tes;MODE=PostgreSQL;
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  main:
    allow-bean-definition-overriding: true

  rsocket:
    server:
      port: 8090